#! /bin/sh

sxhkd &
#xfce4-panel &
nm-applet &

bspc monitor -d code chrome term IV V VI VII gimp com music

bspc config border_width         2
bspc config window_gap          15
bspc config top_padding         21

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
##bspc config wm_name LG3D

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome desktop='^2'
bspc rule -a chrome desktop='^2'
bspc rule -a spotify desktop='^10'
bspc rule -a Slack desktop='^9'
bspc rule -a owncloud desktop='^10'
bspc rule -a dropbox desktop='^10'

compton --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc -b &
syndaemon -i 1 -K d &
sh ~/.fehbg &

wmname LG3D & 

setxkbmap no &

google-chrome &

spotify &

slack &
# xautolock -time 4 -locker "/usr/local/bin/lock -p" -detectsleep & 

xautolock -time 4 -locker "i3lock -i Pictures/trgg.png" -detectsleep & 

killall -q notify-osd &
dunst -config ~/.config/dunstrc &

owncloud &

dropbox start &

#./batMon.sh &

#polybar top &
$HOME/.config/polybar/launch.sh &

# Launch differnent programs and move them
$HOME/.config/bspwm/moveWindow.sh 
